export const movies = [
    {
        id: 1,
        tmdbId: 157336,
        slug: "interstellar",
        title: "Interstellar",
        titleFa: "میان‌ستاره‌ای",
        originalTitle: "Interstellar",
        year: 2014,
        releaseDate: "2014-11-07",
        director: "Christopher Nolan",
        writers: ["Jonathan Nolan", "Christopher Nolan"],
        stars: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine", "Mackenzie Foy"],
        genre: "علمی‌تخیلی",
        genres: ["علمی‌تخیلی", "درام", "ماجراجویی"],
        country: ["USA", "UK"],
        language: ["English"],
        runtime: 169,
        duration: "169 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.7,
        imdbVotes: "2.3M+",
        tmdbRate: 8.4,
        metascore: 74,
        ageRating: "+13",
        likes: "94%",
        budget: "165M$",
        boxOffice: "731M$",
        description: "گروهی از فضانوردان برای نجات بشریت از طریق کرم‌چاله سفری بی‌بازگشت را آغاز می‌کنند.",
        story: "...",
        awards: "Oscar Winner",
        image: "",
        bannerImage: "",
        trailer: "",
        logo: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true,
        isTrending: true,
        isTop250: true,
        isEditorsChoice: true,
        isNew: false,
        isComingSoon: false,
        isExclusive: false,
        watchProviders: ["Netflix"],
        qualities: ["480p", "720p", "1080p", "2160p"],
        subtitleLanguages: ["FA", "EN"],
        dubLanguages: ["FA"],
        tags: ["space", "time", "nolan"],
        keywords: ["wormhole", "NASA", "future"],
        collection: "",
        order: null,
        seasons: null,
        episodes: null
    },

    {
        id: 2,
        tmdbId: 27205,
        slug: "inception",
        title: "Inception",
        titleFa: "تلقین",
        originalTitle: "Inception",
        year: 2010,
        releaseDate: "2010-07-16",
        director: "Christopher Nolan",
        writers: ["Christopher Nolan"],
        stars: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Tom Hardy", "Elliot Page"],
        genre: "معمایی",
        genres: ["معمایی", "اکشن", "علمی‌تخیلی"],
        country: ["USA"],
        language: ["English"],
        runtime: 148,
        duration: "148 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.8,
        imdbVotes: "2.7M+",
        tmdbRate: 8.3,
        metascore: 74,
        ageRating: "+15",
        likes: "91%",
        budget: "160M$",
        boxOffice: "839M$",
        description: "نفوذ به رویاها برای سرقت یا کاشت ایده.",
        story: "...",
        awards: "Oscar Winner",
        image: "",
        bannerImage: "",
        trailer: "",
        logo: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false,
        isTrending: true,
        isTop250: true,
        isEditorsChoice: true,
        isNew: false,
        isComingSoon: false,
        isExclusive: false,
        watchProviders: ["Netflix"],
        qualities: ["480p", "720p", "1080p", "2160p"],
        subtitleLanguages: ["FA", "EN"],
        dubLanguages: ["FA"],
        tags: ["dream", "mind"],
        keywords: ["subconscious", "heist"]
    },

    {
        id: 3,
        tmdbId: 60574,
        slug: "peaky-blinders",
        title: "Peaky Blinders",
        titleFa: "پیکی بلایندرز",
        originalTitle: "Peaky Blinders",
        year: 2013,
        releaseDate: "2013-09-12",
        director: "Steven Knight",
        writers: ["Steven Knight"],
        stars: ["Cillian Murphy", "Paul Anderson", "Helen McCrory"],
        genre: "جنایی",
        genres: ["جنایی", "درام"],
        country: ["UK"],
        language: ["English"],
        runtime: null,
        duration: "6 فصل",
        type: "series",
        status: "Ended",
        imdb: 8.8,
        imdbVotes: "750K+",
        tmdbRate: 8.5,
        metascore: null,
        ageRating: "+18",
        likes: "88%",
        budget: null,
        boxOffice: null,
        description: "خانواده شلبی در بیرمنگام پس از جنگ جهانی اول.",
        story: "...",
        awards: "BAFTA",
        image: "",
        bannerImage: "",
        trailer: "",
        logo: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true,
        isTrending: true,
        isTop250: false,
        isEditorsChoice: true,
        isNew: false,
        isComingSoon: false,
        isExclusive: false,
        seasons: 6,
        episodes: 36,
        watchProviders: ["Netflix"],
        qualities: ["720p", "1080p"],
        subtitleLanguages: ["FA", "EN"],
        dubLanguages: ["FA"],
        tags: ["mafia", "britain"]
    },

    {
        id: 4,
        tmdbId: 155,
        slug: "the-dark-knight",
        title: "The Dark Knight",
        titleFa: "شوالیه تاریکی",
        originalTitle: "The Dark Knight",
        year: 2008,
        releaseDate: "2008-07-18",
        director: "Christopher Nolan",
        writers: ["Jonathan Nolan", "Christopher Nolan"],
        stars: ["Christian Bale", "Heath Ledger", "Gary Oldman"],
        genre: "اکشن",
        genres: ["اکشن", "جنایی", "درام"],
        country: ["USA"],
        language: ["English"],
        runtime: 152,
        duration: "152 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 9.0,
        imdbVotes: "3M+",
        tmdbRate: 8.5,
        metascore: 84,
        ageRating: "+16",
        likes: "96%",
        budget: "185M$",
        boxOffice: "1B$",
        description: "بتمن مقابل جوکر.",
        story: "...",
        awards: "Oscar Winner",
        image: "",
        bannerImage: "",
        trailer: "",
        logo: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true,
        isTrending: true,
        isTop250: true,
        isEditorsChoice: true,
        isNew: false,
        isComingSoon: false,
        isExclusive: false
    },

    {
        id: 5,
        tmdbId: 1396,
        slug: "breaking-bad",
        title: "Breaking Bad",
        titleFa: "برکینگ بد",
        originalTitle: "Breaking Bad",
        year: 2008,
        releaseDate: "2008-01-20",
        director: "Vince Gilligan",
        writers: ["Vince Gilligan"],
        stars: ["Bryan Cranston", "Aaron Paul", "Anna Gunn"],
        genre: "جنایی",
        genres: ["جنایی", "درام"],
        country: ["USA"],
        language: ["English"],
        runtime: null,
        duration: "5 فصل",
        type: "series",
        status: "Ended",
        imdb: 9.5,
        imdbVotes: "2.5M+",
        tmdbRate: 8.9,
        metascore: null,
        ageRating: "+18",
        likes: "97%",
        description: "معلم شیمی وارد دنیای مواد مخدر می‌شود.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true,
        isTrending: true,
        isEditorsChoice: true,
        seasons: 5,
        episodes: 62
    },

    {
        id: 6,
        tmdbId: 1124,
        slug: "the-prestige",
        title: "The Prestige",
        titleFa: "پرستیژ",
        originalTitle: "The Prestige",
        year: 2006,
        releaseDate: "2006-10-20",
        director: "Christopher Nolan",
        writers: ["Jonathan Nolan", "Christopher Nolan"],
        stars: ["Hugh Jackman", "Christian Bale", "Scarlett Johansson"],
        genre: "معمایی",
        genres: ["معمایی", "درام"],
        country: ["USA"],
        language: ["English"],
        runtime: 130,
        duration: "130 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.5,
        tmdbRate: 8.2,
        ageRating: "+14",
        likes: "89%",
        description: "رقابت دو شعبده‌باز.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },

    {
        id: 7,
        tmdbId: 550,
        slug: "fight-club",
        title: "Fight Club",
        titleFa: "باشگاه مشت‌زنی",
        originalTitle: "Fight Club",
        year: 1999,
        releaseDate: "1999-10-15",
        director: "David Fincher",
        writers: ["Jim Uhls"],
        stars: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
        genre: "درام",
        genres: ["درام"],
        country: ["USA"],
        language: ["English"],
        runtime: 139,
        duration: "139 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.8,
        tmdbRate: 8.4,
        ageRating: "+18",
        likes: "92%",
        description: "باشگاهی مخفی برای مبارزه.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },

    {
        id: 8,
        tmdbId: 414906,
        slug: "the-batman",
        title: "The Batman",
        titleFa: "بتمن",
        originalTitle: "The Batman",
        year: 2022,
        releaseDate: "2022-03-04",
        director: "Matt Reeves",
        writers: ["Matt Reeves"],
        stars: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano"],
        genre: "اکشن",
        genres: ["اکشن", "جنایی"],
        country: ["USA"],
        language: ["English"],
        runtime: 176,
        duration: "176 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 7.9,
        tmdbRate: 7.7,
        ageRating: "+16",
        likes: "84%",
        description: "بتمن و ریدلر.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },

    {
        id: 9,
        tmdbId: 872585,
        slug: "oppenheimer",
        title: "Oppenheimer",
        titleFa: "اوپنهایمر",
        originalTitle: "Oppenheimer",
        year: 2023,
        releaseDate: "2023-07-21",
        director: "Christopher Nolan",
        writers: ["Christopher Nolan"],
        stars: ["Cillian Murphy", "Emily Blunt", "Robert Downey Jr."],
        genre: "درام",
        genres: ["درام", "تاریخی"],
        country: ["USA"],
        language: ["English"],
        runtime: 180,
        duration: "180 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.3,
        tmdbRate: 8.1,
        ageRating: "+16",
        likes: "90%",
        description: "زندگی اوپنهایمر.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true
    },

    {
        id: 10,
        tmdbId: 693134,
        slug: "dune-part-two",
        title: "Dune: Part Two",
        titleFa: "تل‌ماسه: بخش دوم",
        originalTitle: "Dune: Part Two",
        year: 2024,
        releaseDate: "2024-03-01",
        director: "Denis Villeneuve",
        writers: ["Jon Spaihts"],
        stars: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"],
        genre: "علمی‌تخیلی",
        genres: ["علمی‌تخیلی", "ماجراجویی"],
        country: ["USA"],
        language: ["English"],
        runtime: 166,
        duration: "166 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.5,
        tmdbRate: 8.3,
        ageRating: "+13",
        likes: "93%",
        description: "ادامه داستان پل آتریدیز.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true
    },

    {
        id: 11,
        tmdbId: 120,
        slug: "the-lord-of-the-rings",
        title: "The Lord of the Rings",
        titleFa: "ارباب حلقه‌ها",
        originalTitle: "The Fellowship of the Ring",
        year: 2001,
        releaseDate: "2001-12-19",
        director: "Peter Jackson",
        writers: ["Fran Walsh"],
        stars: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
        genre: "فانتزی",
        genres: ["فانتزی", "ماجراجویی"],
        country: ["NZ", "USA"],
        language: ["English"],
        runtime: 178,
        duration: "178 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.9,
        tmdbRate: 8.4,
        ageRating: "+13",
        likes: "95%",
        description: "سفر نابودی حلقه.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },

    {
        id: 12,
        tmdbId: 66732,
        slug: "stranger-things",
        title: "Stranger Things",
        titleFa: "چیزهای عجیب",
        originalTitle: "Stranger Things",
        year: 2016,
        releaseDate: "2016-07-15",
        director: "The Duffer Brothers",
        writers: ["The Duffer Brothers"],
        stars: ["Millie Bobby Brown", "Finn Wolfhard", "David Harbour"],
        genre: "علمی‌تخیلی",
        genres: ["علمی‌تخیلی", "ترسناک"],
        country: ["USA"],
        language: ["English"],
        runtime: null,
        duration: "4 فصل",
        type: "series",
        status: "Returning",
        imdb: 8.7,
        tmdbRate: 8.6,
        ageRating: "+16",
        likes: "87%",
        description: "اتفاقات فراطبیعی در هاوکینز.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false,
        seasons: 4
    },

    {
        id: 13,
        tmdbId: 238,
        slug: "the-godfather",
        title: "The Godfather",
        titleFa: "پدرخوانده",
        originalTitle: "The Godfather",
        year: 1972,
        releaseDate: "1972-03-24",
        director: "Francis Ford Coppola",
        writers: ["Mario Puzo", "Francis Ford Coppola"],
        stars: ["Marlon Brando", "Al Pacino", "James Caan"],
        genre: "جنایی",
        genres: ["جنایی", "درام"],
        country: ["USA"],
        language: ["English"],
        runtime: 175,
        duration: "175 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 9.2,
        tmdbRate: 8.7,
        ageRating: "+17",
        likes: "98%",
        description: "خانواده کورلئونه.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },

    {
        id: 14,
        tmdbId: 100088,
        slug: "the-last-of-us",
        title: "The Last of Us",
        titleFa: "آخرین بازمانده از ما",
        originalTitle: "The Last of Us",
        year: 2023,
        releaseDate: "2023-01-15",
        director: "Craig Mazin",
        writers: ["Craig Mazin", "Neil Druckmann"],
        stars: ["Pedro Pascal", "Bella Ramsey"],
        genre: "درام",
        genres: ["درام", "آخرالزمانی"],
        country: ["USA"],
        language: ["English"],
        runtime: null,
        duration: "2 فصل",
        type: "series",
        status: "Returning",
        imdb: 8.8,
        tmdbRate: 8.6,
        ageRating: "+18",
        likes: "91%",
        description: "سفر جول و الی.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true,
        seasons: 2
    },

    {
        id: 15,
        tmdbId: 475557,
        slug: "joker",
        title: "Joker",
        titleFa: "جوکر",
        originalTitle: "Joker",
        year: 2019,
        releaseDate: "2019-10-04",
        director: "Todd Phillips",
        writers: ["Todd Phillips"],
        stars: ["Joaquin Phoenix", "Robert De Niro"],
        genre: "درام",
        genres: ["درام", "جنایی", "روانشناختی"],
        country: ["USA"],
        language: ["English"],
        runtime: 122,
        duration: "122 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.4,
        tmdbRate: 8.1,
        ageRating: "+18",
        likes: "86%",
        description: "تولد جوکر.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 16,
        tmdbId: 13,
        slug: "forrest-gump",
        title: "Forrest Gump",
        titleFa: "فارست گامپ",
        originalTitle: "Forrest Gump",
        year: 1994,
        releaseDate: "1994-07-06",
        director: "Robert Zemeckis",
        writers: ["Eric Roth"],
        stars: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
        genre: "درام",
        genres: ["درام", "عاشقانه"],
        country: ["USA"],
        language: ["English"],
        runtime: 142,
        duration: "142 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.8,
        tmdbRate: 8.5,
        ageRating: "+13",
        likes: "95%",
        description: "داستان زندگی مردی ساده‌دل در مهم‌ترین رویدادهای آمریکا.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 17,
        tmdbId: 680,
        slug: "pulp-fiction",
        title: "Pulp Fiction",
        titleFa: "داستان عامه‌پسند",
        originalTitle: "Pulp Fiction",
        year: 1994,
        releaseDate: "1994-10-14",
        director: "Quentin Tarantino",
        writers: ["Quentin Tarantino"],
        stars: ["John Travolta", "Samuel L. Jackson", "Uma Thurman"],
        genre: "جنایی",
        genres: ["جنایی", "درام"],
        country: ["USA"],
        language: ["English"],
        runtime: 154,
        duration: "154 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.9,
        tmdbRate: 8.5,
        ageRating: "+18",
        likes: "96%",
        description: "چند داستان جنایی که به هم گره می‌خورند.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 18,
        tmdbId: 496243,
        slug: "parasite",
        title: "Parasite",
        titleFa: "انگل",
        originalTitle: "Parasite",
        year: 2019,
        releaseDate: "2019-05-30",
        director: "Bong Joon-ho",
        writers: ["Bong Joon-ho"],
        stars: ["Song Kang-ho", "Choi Woo-shik"],
        genre: "درام",
        genres: ["درام", "هیجانی"],
        country: ["South Korea"],
        language: ["Korean"],
        runtime: 132,
        duration: "132 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.5,
        tmdbRate: 8.5,
        ageRating: "+17",
        likes: "94%",
        description: "برخورد دو خانواده از دو طبقه اجتماعی متفاوت.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true
    },
    {
        id: 19,
        tmdbId: 278,
        slug: "the-shawshank-redemption",
        title: "The Shawshank Redemption",
        titleFa: "رستگاری در شاوشنک",
        originalTitle: "The Shawshank Redemption",
        year: 1994,
        releaseDate: "1994-09-23",
        director: "Frank Darabont",
        writers: ["Frank Darabont"],
        stars: ["Tim Robbins", "Morgan Freeman"],
        genre: "درام",
        genres: ["درام"],
        country: ["USA"],
        language: ["English"],
        runtime: 142,
        duration: "142 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 9.3,
        tmdbRate: 8.7,
        ageRating: "+16",
        likes: "99%",
        description: "امید در دل زندان شاوشنک.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true
    },
    {
        id: 20,
        tmdbId: 424,
        slug: "schindlers-list",
        title: "Schindler's List",
        titleFa: "فهرست شیندلر",
        originalTitle: "Schindler's List",
        year: 1993,
        releaseDate: "1993-12-15",
        director: "Steven Spielberg",
        writers: ["Steven Zaillian"],
        stars: ["Liam Neeson", "Ben Kingsley"],
        genre: "تاریخی",
        genres: ["تاریخی", "درام"],
        country: ["USA"],
        language: ["English"],
        runtime: 195,
        duration: "195 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 9.0,
        tmdbRate: 8.6,
        ageRating: "+16",
        likes: "97%",
        description: "نجات جان هزاران یهودی در جنگ جهانی دوم.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 21,
        tmdbId: 24428,
        slug: "the-avengers",
        title: "The Avengers",
        titleFa: "انتقام‌جویان",
        originalTitle: "The Avengers",
        year: 2012,
        releaseDate: "2012-05-04",
        director: "Joss Whedon",
        writers: ["Joss Whedon"],
        stars: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
        genre: "اکشن",
        genres: ["اکشن", "ابرقهرمانی"],
        country: ["USA"],
        language: ["English"],
        runtime: 143,
        duration: "143 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.0,
        tmdbRate: 7.7,
        ageRating: "+13",
        likes: "91%",
        description: "قهرمانان مارول برای نجات زمین متحد می‌شوند.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 22,
        tmdbId: 299536,
        slug: "avengers-infinity-war",
        title: "Avengers: Infinity War",
        titleFa: "انتقام‌جویان: جنگ ابدیت",
        originalTitle: "Avengers: Infinity War",
        year: 2018,
        releaseDate: "2018-04-27",
        director: "Anthony Russo",
        writers: ["Christopher Markus"],
        stars: ["Robert Downey Jr.", "Chris Hemsworth"],
        genre: "اکشن",
        genres: ["اکشن", "ابرقهرمانی"],
        country: ["USA"],
        language: ["English"],
        runtime: 149,
        duration: "149 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.4,
        tmdbRate: 8.2,
        ageRating: "+13",
        likes: "94%",
        description: "نبرد انتقام‌جویان با تانوس.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true
    },
    {
        id: 23,
        tmdbId: 299534,
        slug: "avengers-endgame",
        title: "Avengers: Endgame",
        titleFa: "انتقام‌جویان: پایان بازی",
        originalTitle: "Avengers: Endgame",
        year: 2019,
        releaseDate: "2019-04-26",
        director: "Anthony Russo",
        writers: ["Christopher Markus"],
        stars: ["Robert Downey Jr.", "Chris Evans"],
        genre: "اکشن",
        genres: ["اکشن", "ابرقهرمانی"],
        country: ["USA"],
        language: ["English"],
        runtime: 181,
        duration: "181 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.4,
        tmdbRate: 8.3,
        ageRating: "+13",
        likes: "95%",
        description: "آخرین نبرد با تانوس.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true
    },
    {
        id: 24,
        tmdbId: 807,
        slug: "se7en",
        title: "Se7en",
        titleFa: "هفت",
        originalTitle: "Se7en",
        year: 1995,
        releaseDate: "1995-09-22",
        director: "David Fincher",
        writers: ["Andrew Kevin Walker"],
        stars: ["Brad Pitt", "Morgan Freeman"],
        genre: "جنایی",
        genres: ["جنایی", "معمایی"],
        country: ["USA"],
        language: ["English"],
        runtime: 127,
        duration: "127 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.6,
        tmdbRate: 8.4,
        ageRating: "+18",
        likes: "94%",
        description: "تعقیب قاتلی که بر اساس هفت گناه کبیره قتل می‌کند.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 25,
        tmdbId: 157336,
        slug: "arrival",
        title: "Arrival",
        titleFa: "ورود",
        originalTitle: "Arrival",
        year: 2016,
        releaseDate: "2016-11-11",
        director: "Denis Villeneuve",
        writers: ["Eric Heisserer"],
        stars: ["Amy Adams", "Jeremy Renner"],
        genre: "علمی‌تخیلی",
        genres: ["علمی‌تخیلی", "درام"],
        country: ["USA"],
        language: ["English"],
        runtime: 116,
        duration: "116 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 7.9,
        tmdbRate: 7.6,
        ageRating: "+13",
        likes: "88%",
        description: "برقراری ارتباط با موجودات فضایی.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 26,
        tmdbId: 634649,
        slug: "spider-man-no-way-home",
        title: "Spider-Man: No Way Home",
        titleFa: "مرد عنکبوتی: راهی به خانه نیست",
        originalTitle: "Spider-Man: No Way Home",
        year: 2021,
        releaseDate: "2021-12-17",
        director: "Jon Watts",
        writers: ["Chris McKenna"],
        stars: ["Tom Holland", "Zendaya"],
        genre: "اکشن",
        genres: ["اکشن", "ابرقهرمانی"],
        country: ["USA"],
        language: ["English"],
        runtime: 148,
        duration: "148 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.2,
        tmdbRate: 8.0,
        ageRating: "+13",
        likes: "92%",
        description: "باز شدن دنیاهای موازی.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true
    },
    {
        id: 27,
        tmdbId: 603,
        slug: "the-matrix",
        title: "The Matrix",
        titleFa: "ماتریکس",
        originalTitle: "The Matrix",
        year: 1999,
        releaseDate: "1999-03-31",
        director: "The Wachowskis",
        writers: ["The Wachowskis"],
        stars: ["Keanu Reeves", "Laurence Fishburne"],
        genre: "علمی‌تخیلی",
        genres: ["علمی‌تخیلی", "اکشن"],
        country: ["USA"],
        language: ["English"],
        runtime: 136,
        duration: "136 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.7,
        tmdbRate: 8.2,
        ageRating: "+16",
        likes: "96%",
        description: "حقیقت دنیای شبیه‌سازی‌شده.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true
    },
    {
        id: 28,
        tmdbId: 497,
        slug: "the-green-mile",
        title: "The Green Mile",
        titleFa: "مسیر سبز",
        originalTitle: "The Green Mile",
        year: 1999,
        releaseDate: "1999-12-10",
        director: "Frank Darabont",
        writers: ["Frank Darabont"],
        stars: ["Tom Hanks", "Michael Clarke Duncan"],
        genre: "درام",
        genres: ["درام", "فانتزی"],
        country: ["USA"],
        language: ["English"],
        runtime: 189,
        duration: "189 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.6,
        tmdbRate: 8.5,
        ageRating: "+16",
        likes: "95%",
        description: "داستان زندانی با قدرتی خارق‌العاده.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 29,
        tmdbId: 372058,
        slug: "your-name",
        title: "Your Name",
        titleFa: "اسم تو",
        originalTitle: "君の名は。",
        year: 2016,
        releaseDate: "2016-08-26",
        director: "Makoto Shinkai",
        writers: ["Makoto Shinkai"],
        stars: ["Ryunosuke Kamiki", "Mone Kamishiraishi"],
        genre: "انیمه",
        genres: ["انیمه", "عاشقانه"],
        country: ["Japan"],
        language: ["Japanese"],
        runtime: 106,
        duration: "106 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.4,
        tmdbRate: 8.5,
        ageRating: "+10",
        likes: "93%",
        description: "تعویض بدن دو نوجوان.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 30,
        tmdbId: 1399,
        slug: "game-of-thrones",
        title: "Game of Thrones",
        titleFa: "بازی تاج و تخت",
        originalTitle: "Game of Thrones",
        year: 2011,
        releaseDate: "2011-04-17",
        director: "David Benioff",
        writers: ["George R. R. Martin"],
        stars: ["Emilia Clarke", "Kit Harington", "Peter Dinklage"],
        genre: "فانتزی",
        genres: ["فانتزی", "درام"],
        country: ["USA"],
        language: ["English"],
        runtime: null,
        duration: "8 فصل",
        type: "series",
        status: "Ended",
        imdb: 9.2,
        tmdbRate: 8.4,
        ageRating: "+18",
        likes: "98%",
        description: "نبرد خاندان‌ها برای تخت آهنین.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true,
        seasons: 8,
        episodes: 73
    }, {
        id: 31,
        tmdbId: 11324,
        slug: "shutter-island",
        title: "Shutter Island",
        titleFa: "جزیره شاتر",
        originalTitle: "Shutter Island",
        year: 2010,
        releaseDate: "2010-02-19",
        director: "Martin Scorsese",
        writers: ["Laeta Kalogridis"],
        stars: ["Leonardo DiCaprio", "Mark Ruffalo", "Ben Kingsley"],
        genre: "معمایی",
        genres: ["معمایی", "هیجانی"],
        country: ["USA"],
        language: ["English"],
        runtime: 138,
        duration: "138 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.2,
        tmdbRate: 8.2,
        ageRating: "+16",
        likes: "91%",
        description: "کارآگاهی برای بررسی ناپدید شدن بیماری روانی به جزیره‌ای مرموز می‌رود.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 32,
        tmdbId: 19404,
        slug: "dilwale-dulhania-le-jayenge",
        title: "Dilwale Dulhania Le Jayenge",
        titleFa: "داماد عاشق عروس را می‌برد",
        originalTitle: "DDLJ",
        year: 1995,
        releaseDate: "1995-10-20",
        director: "Aditya Chopra",
        writers: ["Aditya Chopra"],
        stars: ["Shah Rukh Khan", "Kajol"],
        genre: "عاشقانه",
        genres: ["عاشقانه", "درام"],
        country: ["India"],
        language: ["Hindi"],
        runtime: 189,
        duration: "189 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.0,
        tmdbRate: 8.5,
        ageRating: "+ 13",
        likes: "92 % ",
        description: "یکی ازماندگارترین عاشقانه‌های سینمای هند.",
        image: "",
        bannerImage: "",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 33,
        tmdbId: 122,
        slug: "the-lord-of-the-rings-return-of-the-king",
        title: "The Return of the King",
        titleFa: "بازگشت پادشاه",
        originalTitle: "The Lord of the Rings: The Return of the King",
        year: 2003,
        releaseDate: "2003-12-17",
        director: "Peter Jackson",
        writers: ["Fran Walsh"],
        stars: ["Elijah Wood", "Viggo Mortensen"],
        genre: "فانتزی",
        genres: ["فانتزی", "ماجراجویی"],
        country: ["New Zealand"],
        language: ["English"],
        runtime: 201,
        duration: "201 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 9.0,
        tmdbRate: 8.5,
        ageRating: " + 13",
        likes: "97 % ",
        description: "پایان حماسه ارباب حلقه‌ها.",
        image: "",
        bannerImage: "",
        hasDubbed: true, hasSubtitle: true, isFeatured: true
    },
    {
        id: 34,
        tmdbId: 324857,
        slug: "spider-man-into-the-spider-verse",
        title: "Spider-Man: Into the Spider-Verse",
        titleFa: "مرد عنکبوتی: به درون دنیای عنکبوتی",
        originalTitle: "Spider-Man: Into the Spider-Verse",
        year: 2018,
        releaseDate: "2018-12-14",
        director: "Bob Persichetti",
        writers: ["Phil Lord"],
        stars: ["Shameik Moore", "Jake Johnson"],
        genre: "انیمیشن",
        genres: ["انیمیشن", "اکشن"],
        country: ["USA"],
        language: ["English"],
        runtime: 117,
        duration: "117 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.4,
        tmdbRate: 8.4,
        ageRating: " + 10",
        likes: "94 % ",
        description: " مایلز مورالس به دنیای مردان عنکبوتی وارد می‌شود. ",
        image: "",
        bannerImage: "",
        hasDubbed: true, hasSubtitle: true, isFeatured: false
    },
    {
        id: 35,
        tmdbId: 10195,
        slug: "thor",
        title: "Thor",
        titleFa: "ثور",
        originalTitle: "Thor",
        year: 2011,
        releaseDate: "2011-05-06",
        director: "Kenneth Branagh",
        writers: ["Ashley Miller"],
        stars: ["Chris Hemsworth", "Natalie Portman"],
        genre: "اکشن",
        genres: ["اکشن", "فانتزی"],
        country: ["USA"],
        language: ["English"],
        runtime: 115,
        duration: "115 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 7.0,
        tmdbRate: 6.8,
        ageRating: " + 13",
        likes: "84 % ",
        description: " خدای رعد به زمین تبعید می‌شود. ",
        image: "",
        bannerImage: "",
        hasDubbed: true, hasSubtitle: true, isFeatured: false
    },
    {
        id: 36,
        tmdbId: 315162,
        slug: "puss-in-boots-the-last-wish",
        title: "Puss in Boots: The Last Wish",
        titleFa: "گربه چکمه‌پوش: آخرین آرزو",
        originalTitle: "Puss in Boots: The Last Wish",
        year: 2022,
        releaseDate: "2022-12-21",
        director: "Joel Crawford",
        writers: ["Tom Wheeler"],
        stars: ["Antonio Banderas", "Salma Hayek"],
        genre: "انیمیشن",
        genres: ["انیمیشن", "ماجراجویی"],
        country: ["USA"],
        language: ["English"],
        runtime: 103,
        duration: "103 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.2,
        tmdbRate: 8.2,
        ageRating: " + 7",
        likes: "91 % ",
        description: " گربه چکمه‌پوش آخرین فرصت خود را جستجو می‌کند. ",
        image: "",
        bannerImage: "",
        hasDubbed: true, hasSubtitle: true, isFeatured: false
    },
    {
        id: 37,
        tmdbId: 667257,
        slug: "mission-impossible-dead-reckoning",
        title: "Mission: Impossible - Dead Reckoning",
        titleFa: "ماموریت غیرممکن: روزشمار مرگ",
        originalTitle: "Mission: Impossible - Dead Reckoning",
        year: 2023,
        releaseDate: "2023-07-12",
        director: "Christopher McQuarrie",
        writers: ["Christopher McQuarrie"],
        stars: ["Tom Cruise", "Hayley Atwell"],
        genre: "اکشن",
        genres: ["اکشن", "جاسوسی"],
        country: ["USA"],
        language: ["English"],
        runtime: 163,
        duration: "163 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 7.7,
        tmdbRate: 7.6,
        ageRating: " + 13",
        likes: "89 % ",
        description: " ایتن هانت در برابر هوش مصنوعی خطرناک .",
        image: "",
        bannerImage: "", hasDubbed: true, hasSubtitle: true, isFeatured: true
    },

    {
        id: 38,
        tmdbId: 497698,
        slug: "black-panther-wakanda-forever",
        title: "Black Panther: Wakanda Forever",
        titleFa: "پلنگ سیاه: واکاندا تا ابد",
        originalTitle: "Black Panther: Wakanda Forever",
        year: 2022,
        releaseDate: "2022-11-11",
        director: "Ryan Coogler",
        writers: ["Ryan Coogler"],
        stars: ["Letitia Wright", "Angela Bassett"],
        genre: "اکشن",
        genres: ["اکشن", "ابرقهرمانی"],
        country: ["USA"],
        language: ["English"],
        runtime: 161,
        duration: "161 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 6.7,
        tmdbRate: 7.1,
        ageRating: " + 13",
        likes: "82 % ",
        description: " واکاندا پس از مرگ پادشاه با تهدیدی تازه روبه‌رو می‌شود. ",
        image: "",
        bannerImage: "",
        hasDubbed: true, hasSubtitle: true, isFeatured: false
    },
    {
        id: 39,
        tmdbId: 545611,
        slug: "everything-everywhere-all-at-once",
        title: "Everything Everywhere All at Once",
        titleFa: "همه‌چیز همه‌جا به یکباره",
        originalTitle: "Everything Everywhere All at Once",
        year: 2022,
        releaseDate: "2022-03-25",
        director: "Dan Kwan",
        writers: ["Dan Kwan"],
        stars: ["Michelle Yeoh", "Ke Huy Quan"],
        genre: "علمی‌تخیلی",
        genres: ["علمی‌تخیلی", "کمدی"],
        country: ["USA"],
        language: ["English"],
        runtime: 139,
        duration: "139 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 7.8,
        tmdbRate: 7.8,
        ageRating: " + 16",
        likes: "90 % ",
        description: " سفری عجیب میان جهان‌های موازی .",
        image: "",
        bannerImage: "", hasDubbed: true, hasSubtitle: true, isFeatured: true
    },

    {
        id: 40,
        tmdbId: 76600,
        slug: "avatar-the-way-of-water",
        title: "Avatar: The Way of Water",
        titleFa: "آواتار: راه آب",
        originalTitle: "Avatar: The Way of Water",
        year: 2022,
        releaseDate: "2022-12-16",
        director: "James Cameron",
        writers: ["James Cameron"],
        stars: ["Sam Worthington", "Zoe Saldana"],
        genre: "علمی‌تخیلی",
        genres: ["علمی‌تخیلی", "ماجراجویی"],
        country: ["USA"],
        language: ["English"],
        runtime: 192,
        duration: "192 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 7.5,
        tmdbRate: 7.6,
        ageRating: " + 13",
        likes: "88 % ",
        description: " ادامه ماجراجویی خانواده سالی در پاندورا. ",
        image: "",
        bannerImage: "",
        hasDubbed: true, hasSubtitle: true, isFeatured: true
    },
    {
        id: 41,
        tmdbId: 361743,
        slug: "top-gun-maverick",
        title: "Top Gun: Maverick",
        titleFa: "تاپ گان: ماوریک",
        originalTitle: "Top Gun: Maverick",
        year: 2022,
        releaseDate: "2022-05-27",
        director: "Joseph Kosinski",
        writers: ["Ehren Kruger"],
        stars: ["Tom Cruise", "Miles Teller"],
        genre: "اکشن",
        genres: ["اکشن", "درام"],
        country: ["USA"],
        language: ["English"],
        runtime: 130,
        duration: "130 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.2,
        tmdbRate: 8.2,
        ageRating: " + 13",
        likes: "93 % ",
        description: " بازگشت ماوریک به مدرسه خلبانی .",
        image: "",
        bannerImage: "", hasDubbed: true, hasSubtitle: true, isFeatured: true
    },

    {
        id: 42,
        tmdbId: 98,
        slug: "gladiator",
        title: "Gladiator",
        titleFa: "گلادیاتور",
        originalTitle: "Gladiator",
        year: 2000,
        releaseDate: "2000-05-05",
        director: "Ridley Scott",
        writers: ["David Franzoni"],
        stars: ["Russell Crowe", "Joaquin Phoenix"],
        genre: "حماسی",
        genres: ["حماسی", "اکشن"],
        country: ["USA"],
        language: ["English"],
        runtime: 155,
        duration: "155 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.5,
        tmdbRate: 8.2,
        ageRating: " + 16",
        likes: "95 % ",
        description: " ژنرال رومی برای انتقام به گلادیاتور تبدیل می‌شود. ",
        image: "",
        bannerImage: "",
        hasDubbed: true, hasSubtitle: true, isFeatured: false
    },
    {
        id: 43,
        tmdbId: 354912,
        slug: "coco",
        title: "Coco",
        titleFa: "کوکو",
        originalTitle: "Coco",
        year: 2017,
        releaseDate: "2017-11-22",
        director: "Lee Unkrich",
        writers: ["Adrian Molina"],
        stars: ["Anthony Gonzalez", "Gael García Bernal"],
        genre: "انیمیشن",
        genres: ["انیمیشن", "خانوادگی"],
        country: ["USA"],
        language: ["English"],
        runtime: 105,
        duration: "105 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.4,
        tmdbRate: 8.2,
        ageRating: " + 7",
        likes: "95 % ",
        description: " سفر پسربچه‌ای به سرزمین مردگان .",
        image: "",
        bannerImage: "", hasDubbed: true, hasSubtitle: true, isFeatured: false
    },

    {
        id: 44,
        tmdbId: 438631,
        slug: "dune",
        title: "Dune",
        titleFa: "تل‌ماسه",
        originalTitle: "Dune",
        year: 2021,
        releaseDate: "2021-10-22",
        director: "Denis Villeneuve",
        writers: ["Jon Spaihts"],
        stars: ["Timothée Chalamet", "Rebecca Ferguson"],
        genre: "علمی‌تخیلی",
        genres: ["علمی‌تخیلی", "ماجراجویی"],
        country: ["USA"],
        language: ["English"],
        runtime: 155,
        duration: "155 دقیقه",
        type: "movie",
        status: "Released",
        imdb: 8.0,
        tmdbRate: 7.8,
        ageRating: " + 13",
        likes: "90 % ",
        description: " آغاز حماسه پل آتریدیز. ",
        image: "",
        bannerImage: "",
        hasDubbed: true, hasSubtitle: true, isFeatured: false
    },
    {
        id: 45,
        tmdbId: 1402,
        slug: "the-walking-dead",
        title: "The Walking Dead",
        titleFa: "مردگان متحرک",
        originalTitle: "The Walking Dead",
        year: 2010,
        releaseDate: "2010-10-31",
        director: "Frank Darabont",
        writers: ["Frank Darabont"],
        stars: ["Andrew Lincoln", "Norman Reedus"],
        genre: "ترسناک",
        genres: ["ترسناک", "درام"],
        country: ["USA"],
        language: ["English"],
        runtime: null,
        duration: "11 فصل",
        type: "series",
        status: "Ended",
        imdb: 8.1,
        tmdbRate: 8.1,
        ageRating: " + 18",
        likes: "90 % ",
        description: " بقای انسان‌ها در دنیای زامبی‌ها .",
        image: "",
        bannerImage: "", hasDubbed: true, hasSubtitle: true, isFeatured: true, seasons: 11, episodes: 177
    },

    {
        id: 46,
        tmdbId: 13,
        slug: "forrest-gump",
        title: "Forrest Gump",
        titleFa: "فارست گامپ",
        year: 1994,
        director: "Robert Zemeckis",
        Stars: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
        image: "",
        bannerImage: "",
        description: "داستان زندگی مردی ساده‌دل که ناخواسته در مهم‌ترین اتفاقات تاریخ آمریکا حضور پیدا می‌کند.",
        type: "movie",
        genre: "درام",
        imdb: 8.8,
        duration: "142 دقیقه",
        ageRating: "+13",
        likes: "96%",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 47,
        tmdbId: 424,
        slug: "schindlers-list",
        title: "Schindler's List",
        titleFa: "فهرست شیندلر",
        year: 1993,
        director: "Steven Spielberg",
        Stars: ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes"],
        image: "",
        bannerImage: "",
        description: "کارآفرینی آلمانی جان هزاران یهودی را در جنگ جهانی دوم نجات می‌دهد.",
        type: "movie",
        genre: "تاریخی",
        imdb: 9.0,
        duration: "195 دقیقه",
        ageRating: "+17",
        likes: "98%",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 48,
        tmdbId: 769,
        slug: "goodfellas",
        title: "Goodfellas",
        titleFa: "رفقای خوب",
        year: 1990,
        director: "Martin Scorsese",
        Stars: ["Robert De Niro", "Ray Liotta", "Joe Pesci"],
        image: "",
        bannerImage: "",
        description: "روایت واقعی صعود و سقوط یکی از اعضای مافیا.",
        type: "movie",
        genre: "جنایی",
        imdb: 8.7,
        duration: "146 دقیقه",
        ageRating: "+18",
        likes: "94%",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 49,
        tmdbId: 389,
        slug: "twelve-angry-men",
        title: "12 Angry Men",
        titleFa: "دوازده مرد خشمگین",
        year: 1957,
        director: "Sidney Lumet",
        Stars: ["Henry Fonda", "Lee J. Cobb", "Martin Balsam"],
        image: "",
        bannerImage: "",
        description: "دوازده عضو هیئت منصفه درباره سرنوشت یک نوجوان تصمیم می‌گیرند.",
        type: "movie",
        genre: "درام",
        imdb: 9.0,
        duration: "96 دقیقه",
        ageRating: "+13",
        likes: "99%",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 50,
        tmdbId: 857,
        slug: "saving-private-ryan",
        title: "Saving Private Ryan",
        titleFa: "نجات سرباز رایان",
        year: 1998,
        director: "Steven Spielberg",
        Stars: ["Tom Hanks", "Matt Damon", "Tom Sizemore"],
        image: "",
        bannerImage: "",
        description: "گروهی از سربازان مأمور نجات آخرین بازمانده یک خانواده می‌شوند.",
        type: "movie",
        genre: "جنگی",
        imdb: 8.6,
        duration: "169 دقیقه",
        ageRating: "+17",
        likes: "94%",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 51,
        tmdbId: 85,
        slug: "raiders-of-the-lost-ark",
        title: "Raiders of the Lost Ark",
        titleFa: "ایندیانا جونز و مهاجمان صندوق گمشده",
        year: 1981,
        director: "Steven Spielberg",
        Stars: ["Harrison Ford", "Karen Allen", "Paul Freeman"],
        image: "",
        bannerImage: "",
        description: "ایندیانا جونز برای یافتن صندوق عهد وارد رقابتی خطرناک می‌شود.",
        type: "movie",
        genre: "ماجراجویی",
        imdb: 8.4,
        duration: "115 دقیقه",
        ageRating: "+13",
        likes: "90%",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 52,
        tmdbId: 807,
        slug: "se7en",
        title: "Se7en",
        titleFa: "هفت",
        year: 1995,
        director: "David Fincher",
        Stars: ["Brad Pitt", "Morgan Freeman", "Kevin Spacey"],
        image: "",
        bannerImage: "",
        description: "دو کارآگاه در تعقیب قاتلی زنجیره‌ای هستند که از هفت گناه کبیره الهام می‌گیرد.",
        type: "movie",
        genre: "جنایی",
        imdb: 8.6,
        duration: "127 دقیقه",
        ageRating: "+18",
        likes: "95%",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 53,
        tmdbId: 274,
        slug: "the-silence-of-the-lambs",
        title: "The Silence of the Lambs",
        titleFa: "سکوت بره‌ها",
        year: 1991,
        director: "Jonathan Demme",
        Stars: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn"],
        image: "",
        bannerImage: "",
        description: "یک مأمور اف‌بی‌آی برای دستگیری قاتلی سریالی از کمک هانیبال لکتر استفاده می‌کند.",
        type: "movie",
        genre: "دلهره‌آور",
        imdb: 8.6,
        duration: "118 دقیقه",
        ageRating: "+18",
        likes: "93%",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 54,
        tmdbId: 680,
        slug: "pulp-fiction",
        title: "Pulp Fiction",
        titleFa: "داستان عامه‌پسند",
        year: 1994,
        director: "Quentin Tarantino",
        Stars: ["John Travolta", "Samuel L. Jackson", "Uma Thurman"],
        image: "",
        bannerImage: "",
        description: "چند داستان جنایی به شکلی هوشمندانه در هم تنیده می‌شوند.",
        type: "movie",
        genre: "جنایی",
        imdb: 8.9,
        duration: "154 دقیقه",
        ageRating: "+18",
        likes: "97%",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 55,
        tmdbId: 497,
        slug: "the-green-mile",
        title: "The Green Mile",
        titleFa: "مسیر سبز",
        year: 1999,
        director: "Frank Darabont",
        Stars: ["Tom Hanks", "Michael Clarke Duncan", "David Morse"],
        image: "",
        bannerImage: "",
        description: "نگهبان زندانی با محکومی روبه‌رو می‌شود که قدرتی خارق‌العاده دارد.",
        type: "movie",
        genre: "درام",
        imdb: 8.9,
        duration: "189 دقیقه",
        ageRating: "+16",
        likes: "98%",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 56,
        tmdbId: 324857,
        slug: "spider-man-into-the-spider-verse",
        title: "Spider-Man: Into the Spider-Verse",
        titleFa: "مرد عنکبوتی: به درون دنیای عنکبوتی",
        year: 2018,
        director: "Bob Persichetti",
        Stars: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld"],
        image: "",
        bannerImage: "",
        description: "مایلز مورالس با نسخه‌های مختلف مرد عنکبوتی متحد می‌شود.",
        type: "movie",
        genre: "انیمیشن",
        imdb: 8.4,
        duration: "117 دقیقه",
        ageRating: "+7",
        likes: "92%",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 57,
        tmdbId: 299536,
        slug: "avengers-infinity-war",
        title: "Avengers: Infinity War",
        titleFa: "انتقام‌جویان: جنگ ابدیت",
        year: 2018,
        director: "Anthony Russo",
        Stars: ["Robert Downey Jr.", "Chris Evans", "Josh Brolin"],
        image: "",
        bannerImage: "",
        description: "قهرمانان مارول برای جلوگیری از نقشه تانوس متحد می‌شوند.",
        type: "movie",
        genre: "اکشن",
        imdb: 8.4,
        duration: "149 دقیقه",
        ageRating: "+13",
        likes: "95%",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 58,
        tmdbId: 299534,
        slug: "avengers-endgame",
        title: "Avengers: Endgame",
        titleFa: "انتقام‌جویان: پایان بازی",
        year: 2019,
        director: "Anthony Russo",
        Stars: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
        image: "",
        bannerImage: "",
        description: "بازماندگان انتقام‌جویان برای بازگرداندن جهان تلاش می‌کنند.",
        type: "movie",
        genre: "اکشن",
        imdb: 8.4,
        duration: "181 دقیقه",
        ageRating: "+13",
        likes: "96%",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true
    },
    {
        id: 59,
        tmdbId: 181808,
        slug: "star-wars-the-force-awakens",
        title: "Star Wars: The Force Awakens",
        titleFa: "جنگ ستارگان: نیرو برمی‌خیزد",
        year: 2015,
        director: "J.J. Abrams",
        Stars: ["Daisy Ridley", "John Boyega", "Harrison Ford"],
        image: "",
        bannerImage: "",
        description: "نسل جدید قهرمانان کهکشان در برابر محفل نخست می‌ایستند.",
        type: "movie",
        genre: "علمی‌تخیلی",
        imdb: 7.8,
        duration: "138 دقیقه",
        ageRating: "+13",
        likes: "87%",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: false
    },
    {
        id: 60,
        tmdbId: 603692,
        slug: "john-wick-chapter-4",
        title: "John Wick: Chapter 4",
        titleFa: "جان ویک ۴",
        year: 2023,
        director: "Chad Stahelski",
        Stars: ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård"],
        image: "",
        bannerImage: "",
        description: "جان ویک برای آزادی خود با قدرتمندترین دشمنانش روبه‌رو می‌شود.",
        type: "movie",
        genre: "اکشن",
        imdb: 7.8,
        duration: "169 دقیقه",
        ageRating: "+18",
        likes: "91%",
        hasDubbed: true,
        hasSubtitle: true,
        isFeatured: true
    }
];